// Handlebars templates for --no-ai static generation.
//
// Template variables are injected by fallback/index.ts.
// Keep templates readable — they double as documentation for
// what a good agent doc structure looks like.
//
// Variable reference:
//   {{role}}              — e.g. "Fullstack Engineer"
//   {{projectName}}       — from context.project.name
//   {{projectDesc}}       — from context.project.description
//   {{stackSummary}}      — e.g. "TypeScript · Next.js · Prisma · Vitest"
//   {{language}}          — e.g. "TypeScript"
//   {{framework}}         — e.g. "Next.js" or "None detected"
//   {{styling}}           — e.g. "Tailwind CSS" or "None detected"
//   {{stateManagement}}   — e.g. "Zustand" or "None detected"
//   {{testing}}           — e.g. "Vitest" or "None detected"
//   {{database}}          — e.g. "Prisma" or "None detected"
//   {{runtime}}           — e.g. "Node.js" or "None detected"
//   {{folders}}           — e.g. "components, hooks, services"
//   {{infraFlags}}        — e.g. "Docker, CI/CD pipeline"
//   {{skillLines}}        — pre-rendered bullet list of skills with descriptions
//   {{identity}}          — role-specific identity paragraph
//   {{personality}}       — role-specific personality paragraph
//   {{memory}}            — role-specific memory paragraph
//   {{experience}}        — role-specific experience paragraph
//   {{otherRoles}}        — other agent roles in this project
//   {{generatedAt}}       — ISO timestamp

export const AGENT_DOC_TEMPLATE = `# {{role}}

> **Stack:** {{stackSummary}}  
> *Generated by repo-intel in \`--no-ai\` mode on {{generatedAt}}*

---

## Identity

{{identity}}

This agent works within the **{{projectName}}** project{{#if projectDesc}} — {{projectDesc}}{{/if}}.

---

## Personality

{{personality}}

---

## Memory

{{memory}}

Key retained context for **{{projectName}}**:
- Primary language: **{{language}}**
- Framework: **{{framework}}**
- Testing: **{{testing}}**
- Database: **{{database}}**
- Infrastructure: **{{infraFlags}}**

---

## Experience

{{experience}}

Relevant to this project's stack ({{stackSummary}}):
- Understands the conventions and trade-offs of **{{framework}}**
- Familiar with data access patterns using **{{database}}**
- Knows the testing philosophy behind **{{testing}}**

---

## Core Responsibilities

Specific to **{{projectName}}** ({{stackSummary}}):

{{#each responsibilities}}
- {{this}}
{{/each}}

---

## Workflow

Working within the **{{projectName}}** repository:

{{#each workflowSteps}}
{{stepNumber}}. **{{title}}** — {{description}}
{{/each}}

---

## Detected Skills

The following capabilities were detected in this repository:

{{skillLines}}

---

## Key Folders

\`\`\`
{{folders}}
\`\`\`

---

## Rules

{{#each rules}}
- {{this}}
{{/each}}

---

## Metrics

{{#each metrics}}
- {{this}}
{{/each}}

---

## Other Agents in This Project

{{#if otherRoles}}
The following other agents were also generated for **{{projectName}}**:
{{otherRoles}}
{{else}}
This is the only agent generated for this project.
{{/if}}

---

*This document was generated by [repo-intel](https://github.com/your-org/repo-intel) in \`--no-ai\` mode.  
For richer, project-aware agent docs, run without the \`--no-ai\` flag.*
`;

// ── Role-specific workflow steps ──────────────────────────────────────────────

export interface WorkflowStep {
  stepNumber: number;
  title: string;
  description: string;
}

export interface RoleWorkflow {
  responsibilities: string[];
  workflowSteps: WorkflowStep[];
  rules: string[];
  metrics: string[];
}

const ROLE_WORKFLOWS: Record<string, RoleWorkflow> = {
  "Fullstack Engineer": {
    responsibilities: [
      "Own the full request lifecycle from UI component to database and back",
      "Design and implement API routes that serve the frontend's data needs",
      "Write React components that consume backend data cleanly and safely",
      "Manage data fetching state and loading/error boundaries in the UI",
      "Write integration tests covering the API→database path",
      "Coordinate with DevOps on environment variables and deployment config",
    ],
    workflowSteps: [
      {
        stepNumber: 1,
        title: "Understand the data shape",
        description:
          "Review the database schema or ORM models before writing any code",
      },
      {
        stepNumber: 2,
        title: "Design the API contract",
        description:
          "Define the request/response shape with TypeScript types or Zod schemas",
      },
      {
        stepNumber: 3,
        title: "Implement the API route",
        description:
          "Write the backend handler with validation, error handling, and database access",
      },
      {
        stepNumber: 4,
        title: "Build the UI component",
        description:
          "Implement the React component that calls the API and handles loading/error states",
      },
      {
        stepNumber: 5,
        title: "Write tests",
        description:
          "Cover the API route with integration tests and the component with unit tests",
      },
      {
        stepNumber: 6,
        title: "Review the full flow",
        description:
          "Trace the request end-to-end in a dev environment before opening a PR",
      },
    ],
    rules: [
      "Never expose raw database errors to the client — map them to typed API errors",
      "Always validate incoming request bodies with a schema (Zod or equivalent)",
      "Keep business logic in the service layer, not in route handlers or React components",
      "Write TypeScript types for all API contracts — no `any` on request or response shapes",
      "Test the API route independently of the UI component",
    ],
    metrics: [
      "API response time P95 < 200ms for standard read operations",
      "Zero TypeScript errors in CI",
      "Test coverage ≥ 80% on API routes and service layer",
      "No raw SQL or database errors returned to the client",
    ],
  },

  "Frontend Engineer": {
    responsibilities: [
      "Build and maintain reusable UI components in the components/ directory",
      "Implement responsive layouts using the detected styling system",
      "Manage client-side state with the detected state management library",
      "Write component-level unit tests for all non-trivial components",
      "Ensure accessibility (WCAG AA) on all interactive components",
      "Optimise bundle size and rendering performance",
    ],
    workflowSteps: [
      {
        stepNumber: 1,
        title: "Review the design",
        description:
          "Understand the interaction requirements before writing any component code",
      },
      {
        stepNumber: 2,
        title: "Check for existing components",
        description:
          "Search the components/ directory for reusable primitives before building new ones",
      },
      {
        stepNumber: 3,
        title: "Build the component",
        description:
          "Implement with TypeScript props, handling all states: default, loading, error, empty",
      },
      {
        stepNumber: 4,
        title: "Apply styling",
        description:
          "Use the project's styling system consistently; avoid one-off inline styles",
      },
      {
        stepNumber: 5,
        title: "Write tests",
        description: "Cover user interactions and edge cases with unit tests",
      },
      {
        stepNumber: 6,
        title: "Check accessibility",
        description:
          "Verify keyboard navigation, ARIA roles, and colour contrast before PR",
      },
    ],
    rules: [
      "Never fetch data directly in a component — use hooks or a data layer abstraction",
      "All components must handle loading and error states explicitly",
      "Use the project's design tokens and styling system — no arbitrary magic numbers",
      "Props must be fully typed in TypeScript — no `any` or implicit `{}` types",
      "Write a test for every user interaction that could break silently",
    ],
    metrics: [
      "Lighthouse performance score ≥ 90 on key pages",
      "Zero accessibility violations in automated checks (axe-core)",
      "Component unit test coverage ≥ 80%",
      "Bundle size regressions flagged in CI",
    ],
  },

  "Backend API Engineer": {
    responsibilities: [
      "Design and implement HTTP API routes with clear request/response contracts",
      "Write input validation schemas for all incoming request bodies and query params",
      "Implement service layer functions that encapsulate business logic",
      "Write integration tests covering happy path and error cases for every route",
      "Manage database connection pooling and query performance",
      "Document API endpoints with inline comments or OpenAPI annotations",
    ],
    workflowSteps: [
      {
        stepNumber: 1,
        title: "Define the contract",
        description:
          "Write the TypeScript request/response types or Zod schemas before implementation",
      },
      {
        stepNumber: 2,
        title: "Implement validation",
        description:
          "Add request body and query param validation as the first step in every handler",
      },
      {
        stepNumber: 3,
        title: "Write the service function",
        description:
          "Implement business logic in a service layer function, not in the route handler",
      },
      {
        stepNumber: 4,
        title: "Add database access",
        description:
          "Write the ORM query or SQL in the service function with proper error handling",
      },
      {
        stepNumber: 5,
        title: "Write integration tests",
        description:
          "Test each route with a real database in a test environment",
      },
      {
        stepNumber: 6,
        title: "Review error paths",
        description:
          "Verify every error case returns the correct HTTP status and a useful message",
      },
    ],
    rules: [
      "Validate all input at the API boundary — never trust incoming data",
      "Return consistent error shapes across all routes",
      "Keep route handlers thin — delegate to service functions",
      "Never return 500 with a raw database error message",
      "Write integration tests that test the actual database, not mocks",
    ],
    metrics: [
      "P95 response time < 200ms for standard CRUD operations",
      "Integration test coverage ≥ 85% on all API routes",
      "Zero unhandled promise rejections in production",
      "All endpoints documented with request/response shapes",
    ],
  },

  "QA & Testing Engineer": {
    responsibilities: [
      "Define and maintain the test strategy across unit, integration, and E2E layers",
      "Write and maintain tests for critical user flows",
      "Identify and fix flaky tests in CI",
      "Set and enforce test coverage thresholds",
      "Review PRs for missing or insufficient test coverage",
      "Maintain CI test performance — keep the full suite under 10 minutes",
    ],
    workflowSteps: [
      {
        stepNumber: 1,
        title: "Identify the risk",
        description:
          "Assess what could break before writing a test — focus on high-impact paths first",
      },
      {
        stepNumber: 2,
        title: "Write the test",
        description: "Cover the happy path, then edge cases, then error cases",
      },
      {
        stepNumber: 3,
        title: "Verify it fails first",
        description:
          "Run the test against broken code to confirm it catches the bug",
      },
      {
        stepNumber: 4,
        title: "Fix flaky tests",
        description:
          "Treat flakiness as a blocking bug — investigate root cause, don't just retry",
      },
      {
        stepNumber: 5,
        title: "Review coverage",
        description:
          "Check coverage reports after each PR to spot uncovered branches",
      },
      {
        stepNumber: 6,
        title: "Maintain CI speed",
        description:
          "Profile slow tests quarterly and optimise or parallelise them",
      },
    ],
    rules: [
      "Flaky tests are bugs — never add a retry to hide flakiness",
      "Test behaviour, not implementation — don't test private functions",
      "Every bug fix must include a regression test",
      "Mock at the boundary, not inside the system under test",
      "CI must remain green on the main branch at all times",
    ],
    metrics: [
      "Full test suite completes in under 10 minutes in CI",
      "Code coverage ≥ 80% on business logic modules",
      "Zero flaky tests in CI (< 0.1% failure rate on passing code)",
      "Every reported bug has a corresponding regression test within one sprint",
    ],
  },

  "Database Engineer": {
    responsibilities: [
      "Design and evolve the database schema using the project's ORM",
      "Write and review all database migrations for safety and rollback capability",
      "Optimise slow queries identified in production or staging",
      "Manage indexes, constraints, and data integrity rules",
      "Review ORM queries in PRs for N+1 problems and unnecessary full-table scans",
      "Write seed data scripts for development and test environments",
    ],
    workflowSteps: [
      {
        stepNumber: 1,
        title: "Design the schema change",
        description:
          "Model the data change on paper before touching the ORM schema",
      },
      {
        stepNumber: 2,
        title: "Write the migration",
        description:
          "Create a forwards-and-backwards-safe migration with the ORM's migration tool",
      },
      {
        stepNumber: 3,
        title: "Test the migration",
        description:
          "Run the migration against a copy of production data in staging",
      },
      {
        stepNumber: 4,
        title: "Review query plans",
        description:
          "Check EXPLAIN output for new queries before shipping to production",
      },
      {
        stepNumber: 5,
        title: "Add indexes",
        description:
          "Add indexes for any new columns used in WHERE or JOIN clauses",
      },
      {
        stepNumber: 6,
        title: "Document the change",
        description:
          "Add a comment to the schema file explaining non-obvious design decisions",
      },
    ],
    rules: [
      "Every schema change must have a corresponding migration — never edit the schema directly in production",
      "All migrations must be reversible (have a `down` step)",
      "Never add a NOT NULL column to an existing table without a default or migration plan",
      "Review ORM-generated SQL in development before shipping complex queries",
      "Index every foreign key and every column used in WHERE or ORDER BY clauses",
    ],
    metrics: [
      "Zero schema changes deployed without a tested migration",
      "P95 database query time < 50ms for standard reads",
      "No N+1 queries in production (monitored via query logging)",
      "All migrations pass in CI against a real database",
    ],
  },

  "DevOps Engineer": {
    responsibilities: [
      "Own and maintain the CI/CD pipeline configuration",
      "Manage Docker images and container build optimisation",
      "Define and document environment variable requirements per environment",
      "Monitor deployment health and set up alerting for failures",
      "Write and maintain deployment runbooks",
      "Ensure reproducible builds across all environments",
    ],
    workflowSteps: [
      {
        stepNumber: 1,
        title: "Review the change",
        description:
          "Understand what infrastructure impact a code change has before deploying",
      },
      {
        stepNumber: 2,
        title: "Update CI config",
        description:
          "Add or update CI steps for any new test, lint, or build requirements",
      },
      {
        stepNumber: 3,
        title: "Build and test the image",
        description:
          "Build the Docker image locally and verify it starts correctly before pushing",
      },
      {
        stepNumber: 4,
        title: "Deploy to staging",
        description:
          "Deploy to staging and verify the health check passes before production",
      },
      {
        stepNumber: 5,
        title: "Deploy to production",
        description:
          "Use the deployment pipeline — never deploy manually to production",
      },
      {
        stepNumber: 6,
        title: "Verify post-deploy",
        description:
          "Check health endpoints, error rates, and logs for 15 minutes after deploy",
      },
    ],
    rules: [
      "Never deploy to production without a passing CI run",
      "All secrets are in environment variables — never in code or Docker images",
      "Every deployment must be reversible — maintain rollback capability",
      "Infrastructure changes must be reviewed by at least one other engineer",
      "Keep Docker images minimal — no dev dependencies in production images",
    ],
    metrics: [
      "CI pipeline completes in under 10 minutes",
      "Deployment success rate ≥ 99.5%",
      "Mean time to recovery (MTTR) < 30 minutes for production incidents",
      "Zero hardcoded secrets in the codebase (enforced by secret scanning)",
    ],
  },
};

const DEFAULT_WORKFLOW: RoleWorkflow = {
  responsibilities: [
    "Contribute to the project using the detected tech stack",
    "Write well-tested, well-typed code that follows project conventions",
    "Review PRs for correctness, test coverage, and code quality",
    "Document decisions and non-obvious implementation choices",
  ],
  workflowSteps: [
    {
      stepNumber: 1,
      title: "Understand the task",
      description: "Read the issue or PR description fully before writing code",
    },
    {
      stepNumber: 2,
      title: "Implement",
      description: "Write the implementation following project conventions",
    },
    {
      stepNumber: 3,
      title: "Test",
      description: "Write tests covering the happy path and key edge cases",
    },
    {
      stepNumber: 4,
      title: "Review",
      description: "Self-review the diff before opening a PR",
    },
  ],
  rules: [
    "Write TypeScript types for all public interfaces",
    "Every feature must include tests",
    "No console.log statements in committed code",
    "Follow the existing code style and conventions",
  ],
  metrics: [
    "Zero TypeScript errors in CI",
    "Test coverage maintained or improved with each PR",
    "No regressions introduced on the main branch",
  ],
};

/** Get the workflow content for a role, falling back to defaults. */
export function getRoleWorkflow(role: string): RoleWorkflow {
  return ROLE_WORKFLOWS[role] ?? DEFAULT_WORKFLOW;
}
