import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentDoc, AnalyzeOptions, RepoContext } from "../types.js";
import { generateAgentDocs } from "../ai/index.js";
import { generateStatic } from "../fallback/index.js";

/**
 * Write AgentDoc[] → agents/*.md + AGENTS.md index file.
 */
export async function writeAgentDocs(
  context: RepoContext,
  opts: Pick<AnalyzeOptions, "outputDir" | "provider" | "model" | "noAi">,
): Promise<void> {
  const outputDir = opts.outputDir ?? "agents";
  await mkdir(outputDir, { recursive: true });

  let docs: AgentDoc[];

  if (opts.noAi) {
    docs = generateStatic(context);
  } else {
    try {
      docs = await generateAgentDocs(context, {
        provider: opts.provider,
        model: opts.model,
      });
    } catch (err) {
      console.warn(
        `[repo-intel] AI generation failed, falling back to static templates: ${err}`,
      );
      docs = generateStatic(context);
    }
  }

  // Write individual agent files
  await Promise.all(
    docs.map((doc) =>
      writeFile(join(outputDir, `${doc.role_id}.md`), doc.content, "utf-8"),
    ),
  );

  // Write the AGENTS.md index
  const index = buildIndex(docs);
  await writeFile(join(outputDir, "AGENTS.md"), index, "utf-8");

  console.log(`[repo-intel] Written ${docs.length} agent docs to ./${outputDir}/`);
}

function buildIndex(docs: AgentDoc[]): string {
  const lines = [
    "# Agent Documentation Index",
    "",
    "This file is auto-generated by repo-intel. Do not edit manually.",
    "",
    "## Agents",
    "",
  ];

  for (const doc of docs) {
    lines.push(`- [${doc.title}](./${doc.role_id}.md)`);
  }

  return lines.join("\n");
}

// Re-export as the public `generate` API
export const generate = writeAgentDocs;
