import { mkdirSync, writeFileSync } from "fs";
import { join, dirname, relative } from "path";
import type { AgentDoc, RepoContext } from "../types";

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Write generated agent docs to disk.
 *
 * In normal mode:
 *   - Creates `outputDir/` if it doesn't exist
 *   - Writes one `.md` file per doc
 *   - Writes `AGENTS.md` index at the repo root (one level above `outputDir`)
 *
 * In dry-run mode:
 *   - Prints all doc content to stdout with separators
 *   - Prints the AGENTS.md content to stdout
 *   - Does NOT write any files
 */
export function writeAgentDocs(
  docs: AgentDoc[],
  outputDir: string,
  dryRun = false,
): void {
  if (docs.length === 0) {
    console.warn("warn: no agent docs to write");
    return;
  }

  if (dryRun) {
    printDryRun(docs, outputDir);
    return;
  }

  // ── Create output directory ───────────────────────────────────────────────
  mkdirSync(outputDir, { recursive: true });

  // ── Write individual agent docs ───────────────────────────────────────────
  for (const doc of docs) {
    const filePath = join(outputDir, doc.filename);
    writeFileSync(filePath, doc.content, "utf8");
    console.log(`  ✓ ${relative(process.cwd(), filePath)}`);
  }

  // ── Write AGENTS.md index ─────────────────────────────────────────────────
  writeAgentsIndex(docs, outputDir);
}

// ── AGENTS.md index ───────────────────────────────────────────────────────────

/**
 * Write an AGENTS.md index file at the repo root (parent of `outputDir`).
 *
 * The index lists all generated agent docs with relative links so any
 * Markdown viewer or AI assistant can discover the full agent team.
 */
function writeAgentsIndex(docs: AgentDoc[], outputDir: string): void {
  // Place AGENTS.md one level above the agents/ folder — at repo root
  const indexPath = join(dirname(outputDir), "AGENTS.md");
  const agentsDir = outputDir.split("/").pop() ?? "agents";

  const content = buildAgentsIndexContent(docs, agentsDir);

  writeFileSync(indexPath, content, "utf8");
  console.log(`  ✓ ${relative(process.cwd(), indexPath)}`);
}

export function buildAgentsIndexContent(
  docs: AgentDoc[],
  agentsDir = "agents",
): string {
  const now = new Date().toUTCString();
  const lines = [
    "# Agent Index",
    "",
    `> Generated by [repo-intel](https://github.com/your-org/repo-intel) on ${now}`,
    "",
    "## Available Agents",
    "",
    "The following AI agent personas have been generated for this repository.",
    "Each file describes an agent's identity, responsibilities, workflow, and rules.",
    "",
    ...docs.map((d) => `- [**${d.role}**](./${agentsDir}/${d.filename})`),
    "",
    "---",
    "",
    "## Usage",
    "",
    "To use these agents with an AI coding assistant, reference the relevant file",
    "at the start of your session. For example, in Claude:",
    "",
    "```",
    `Read ./${agentsDir}/${docs[0]?.filename ?? "agent.md"} and adopt that persona for this session.`,
    "```",
    "",
    "---",
    "",
    "*Re-generate at any time with `repo-intel generate`*",
  ];

  return lines.join("\n");
}

// ── Dry-run output ────────────────────────────────────────────────────────────

function printDryRun(docs: AgentDoc[], outputDir: string): void {
  const separator = "─".repeat(60);
  const agentsDir = outputDir.split("/").pop() ?? "agents";

  console.log(`\n${separator}`);
  console.log(
    `  DRY RUN — ${docs.length} agent doc(s) would be written to: ${outputDir}`,
  );
  console.log(separator);

  for (const doc of docs) {
    console.log(`\n${"━".repeat(60)}`);
    console.log(`  📄  ${agentsDir}/${doc.filename}`);
    console.log(
      `  Role: ${doc.role}  |  ${doc.content.length} chars  |  confidence: ${(doc.confidence * 100).toFixed(0)}%`,
    );
    console.log("━".repeat(60));
    console.log(doc.content);
  }

  // Also print what AGENTS.md would contain
  console.log(`\n${"━".repeat(60)}`);
  console.log(`  📄  AGENTS.md  (index — written at repo root)`);
  console.log("━".repeat(60));
  console.log(buildAgentsIndexContent(docs, agentsDir));

  console.log(`\n${separator}`);
  console.log(`  DRY RUN complete — no files written`);
  console.log(separator);
}

// ── Summary helpers ───────────────────────────────────────────────────────────

/** Print a human-readable generation summary to stdout. */
export function printSummary(
  docs: AgentDoc[],
  errors: Array<{ role: string; error: string }>,
  context: RepoContext,
  durationMs: number,
  usedAi: boolean,
): void {
  const mode = usedAi ? "AI" : "--no-ai (static)";
  const projectName = context.project.name;
  const stack = [context.stack.language, context.stack.framework]
    .filter(Boolean)
    .join(" + ");

  console.log("");
  console.log(`  repo-intel — ${projectName} (${stack})`);
  console.log(
    `  Mode: ${mode}  |  ${docs.length} doc(s) generated in ${durationMs}ms`,
  );

  if (errors.length > 0) {
    console.log(`  ⚠  ${errors.length} role(s) failed:`);
    for (const e of errors) {
      console.log(`     • ${e.role}: ${e.error}`);
    }
  }

  console.log("");
}
